import { Ticket } from "@/types";

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: "tk-101",
    ticket_number: 101,
    user_id: "usr-lucas",
    user_nombre: "Lucas Benítez",
    user_email: "lucas.maker.rosario@gmail.com",
    user_whatsapp: "+54 9 341 555-1234",
    titulo: "ESP32 NodeMCU en Boot Loop tras update OTA",
    descripcion: "Subí una actualización vía OTA con Arduino IDE y la placa quedó reiniciando indefinidamente. En el monitor serial me tira 'rst:0x10 (RTCWDT_RTC_RESET),boot:0x13'. No me deja flashear por USB.",
    tipo_chip: "ESP32-WROOM-32",
    estado: "en_reparacion",
    prioridad: "alta",
    nota_interna: "Memoria SPI flash con sectores corruptos. Requiere full erase vía esptool y cargar bootloader nuevo.",
    adjunto_url: "/uploads/log_serial_bootloop.txt",
    created_at: "2026-08-28T14:30:00Z",
    updated_at: "2026-08-29T10:15:00Z",
    messages: [
      {
        id: "msg-1",
        ticket_id: "tk-101",
        sender_id: "usr-lucas",
        sender_name: "Lucas Benítez",
        sender_role: "cliente",
        mensaje: "Hola Exequiel! Te dejé el detalle arriba. ¿Se podrá recuperar o se quemó la flash?",
        created_at: "2026-08-28T14:32:00Z",
      },
      {
        id: "msg-2",
        ticket_id: "tk-101",
        sender_id: "usr-admin",
        sender_name: "Exequiel (Chispa32)",
        sender_role: "admin",
        mensaje: "¡Hola Lucas! El reset es por Watchdog de RTC. La placa está sana eléctricamente. Ya le estamos haciendo un erase completo de flash para restaurar el bootloader.",
        created_at: "2026-08-28T19:45:00Z",
      },
    ],
  },
  {
    id: "tk-102",
    ticket_number: 102,
    user_id: "usr-marina",
    user_nombre: "Marina Rossi",
    user_email: "mrossi.arq@outlook.com",
    user_whatsapp: "+54 9 341 678-9012",
    titulo: "Flasheo de módulos Sonoff con ESPHome para Home Assistant",
    descripcion: "Tengo 2 módulos Sonoff Mini para automatizar luces de mi estudio. Necesito que queden con ESPHome configurado para integrarse directo a mi Home Assistant local.",
    tipo_chip: "Sonoff Mini (ESP8266)",
    estado: "recibido",
    prioridad: "media",
    nota_interna: "Coordinar entrega de módulos por zona centro.",
    created_at: "2026-08-30T18:00:00Z",
    updated_at: "2026-08-30T18:00:00Z",
    messages: [
      {
        id: "msg-3",
        ticket_id: "tk-102",
        sender_id: "usr-marina",
        sender_name: "Marina Rossi",
        sender_role: "cliente",
        mensaje: "Hola, ¿cómo estás? ¿Te los puedo acercar por zona centro?",
        created_at: "2026-08-30T18:05:00Z",
      }
    ],
  },
  {
    id: "tk-103",
    ticket_number: 103,
    user_id: "usr-pablo",
    user_nombre: "Pablo Gómez",
    user_email: "pablo.g@estudiantes.unr.edu.ar",
    user_whatsapp: "+54 9 341 432-5678",
    titulo: "Fuga de memoria Heap al publicar en MQTT cada 500ms",
    descripcion: "Proyecto con ESP32-S3 y sensores I2C. A las 2 horas se congela el core 0 por falta de memoria libre. Necesitamos auditar el código en PlatformIO.",
    tipo_chip: "ESP32-S3-DevKitC",
    estado: "resuelto",
    prioridad: "urgente",
    nota_interna: "Resuelto. Fuga corregida reemplazando String dinámico por buffer estático char[] en el callback MQTT.",
    created_at: "2026-08-25T11:00:00Z",
    updated_at: "2026-08-27T16:20:00Z",
    messages: [
      {
        id: "msg-4",
        ticket_id: "tk-103",
        sender_id: "usr-admin",
        sender_name: "Exequiel (Chispa32)",
        sender_role: "admin",
        mensaje: "Pablo, encontramos la fuga y ya está optimizado el código con buffer estático char. Te enviamos el archivo corregido.",
        created_at: "2026-08-27T15:00:00Z",
      }
    ],
  },
];
